# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
# Template #1: General project. Test it using existing `platformio.ini`.
# platformio ci src/main.cpp --project-conf platformio.ini

language: python
python:
   - "2.7"

install:
   - pip install -U platformio

script:
   - cd hardware/device && platformio run
   - cd hardware/tester && platformio run

