// `data` is loaded in from the data.js file, which is generated by parse.rb

$(document).ready(() => {
  $('#defaults-graph').tufteBar({
    data: data,
  });

  $('#static-properties-graph').tufteBar({
    data: data,
    barWidth: 0.7,
    barLabel: 'Y',
    axisLabel: 'X',
    color: '#aa0000',
  });

  $('#dynamic-properties-graph').tufteBar({
    data: data,
    barWidth: function(i) {
      return 0.5 + (i % 2) * 0.2;
    },
    barLabel: function(i) {
      return this[0];
    },
    axisLabel: function(i) {
      return this[1].label;
    },
    color: function(i) {
      return this[1].color || ['#E57536', '#82293B'][i % 2];
    },
  });
});
